const ExcelJS = require('exceljs');

/**
 * Excel Report Service
 * Handles Excel generation for sales reports with advanced formatting
 */
class ExcelReportService {
  
  /**
   * Generate Excel file for sales report
   * @param {Object} report - Report object from database
   * @returns {Buffer} Excel buffer
   */
  static async generateSalesReportExcel(report) {
    try {
      console.log(`Generating Excel for report: ${report.reportId}`);
      
      // Create new workbook
      const workbook = new ExcelJS.Workbook();
      
      // Set workbook properties
      workbook.creator = 'Sunlit CRM';
      workbook.lastModifiedBy = report.generatedBy?.name || 'System';
      workbook.created = new Date();
      workbook.modified = new Date();
      
      // Create worksheets
      await this.createSummarySheet(workbook, report);
      await this.createKPIsSheet(workbook, report);
      await this.createLeadAnalysisSheet(workbook, report);
      await this.createProductPerformanceSheet(workbook, report);
      await this.createTrendsSheet(workbook, report);
      await this.createRawDataSheet(workbook, report);
      
      // Generate buffer
      const buffer = await workbook.xlsx.writeBuffer();
      console.log(`Excel generated successfully for report ${report.reportId}`);
      
      return buffer;
      
    } catch (error) {
      console.error('Error in generateSalesReportExcel:', error);
      throw new Error(`Failed to generate Excel report: ${error.message}`);
    }
  }
  
  /**
   * Create Summary worksheet
   */
  static async createSummarySheet(workbook, report) {
    const worksheet = workbook.addWorksheet('Summary', {
      pageSetup: { paperSize: 9, orientation: 'portrait' }
    });
    
    const data = report.reportData;
    const kpis = data.kpis || {};
    
    // Set column widths
    worksheet.columns = [
      { key: 'metric', width: 25 },
      { key: 'value', width: 20 },
      { key: 'status', width: 15 }
    ];
    
    // Add header
    worksheet.mergeCells('A1:C1');
    const headerRow = worksheet.getCell('A1');
    headerRow.value = `Sales Performance Report - ${report.reportName}`;
    headerRow.font = { name: 'Arial', size: 16, bold: true, color: { argb: 'FF2563EB' } };
    headerRow.alignment = { horizontal: 'center', vertical: 'middle' };
    headerRow.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFF1F5F9' } };
    
    // Add report info
    worksheet.addRow([]);
    worksheet.addRow(['Report Period:', `${this.formatDate(report.reportPeriod.startDate)} to ${this.formatDate(report.reportPeriod.endDate)}`]);
    worksheet.addRow(['Generated On:', this.formatDateTime(report.createdAt)]);
    worksheet.addRow(['Generated By:', report.generatedBy?.name || 'System']);
    worksheet.addRow([]);
    
    // Add KPIs section
    const kpisHeaderRow = worksheet.addRow(['Key Performance Indicators', '', '']);
    kpisHeaderRow.font = { bold: true, size: 14 };
    kpisHeaderRow.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFE5E7EB' } };
    
    // KPIs data
    const kpiData = [
      ['Total Leads', this.formatNumber(kpis.totalLeads), this.getKPIStatus(kpis.totalLeads, 'leads')],
      ['Converted Leads', this.formatNumber(kpis.convertedLeads), this.getKPIStatus(kpis.convertedLeads, 'conversions')],
      ['Conversion Rate', this.formatPercentage(kpis.conversionRate), this.getKPIStatus(kpis.conversionRate, 'rate')],
      ['Total Quotations', this.formatNumber(kpis.totalQuotations), this.getKPIStatus(kpis.totalQuotations, 'quotations')],
      ['Approved Quotations', this.formatNumber(kpis.approvedQuotations), this.getKPIStatus(kpis.approvedQuotations, 'approvals')],
      ['Quotation Success Rate', this.formatPercentage(kpis.quotationSuccessRate), this.getKPIStatus(kpis.quotationSuccessRate, 'rate')],
      ['Total Revenue', this.formatCurrency(kpis.totalRevenue), this.getKPIStatus(kpis.totalRevenue, 'revenue')],
      ['Average Deal Size', this.formatCurrency(kpis.averageDealSize), this.getKPIStatus(kpis.averageDealSize, 'dealsize')],
      ['Pipeline Value', this.formatCurrency(kpis.pipelineValue), this.getKPIStatus(kpis.pipelineValue, 'pipeline')],
      ['Activities Completed', this.formatNumber(kpis.activitiesCompleted), this.getKPIStatus(kpis.activitiesCompleted, 'activities')]
    ];
    
    kpiData.forEach(row => {
      const dataRow = worksheet.addRow(row);
      dataRow.getCell(1).font = { bold: true };
      dataRow.getCell(2).alignment = { horizontal: 'right' };
      dataRow.getCell(3).alignment = { horizontal: 'center' };
      
      // Color code status
      const statusCell = dataRow.getCell(3);
      if (statusCell.value === 'Excellent') {
        statusCell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF10B981' } };
        statusCell.font = { color: { argb: 'FFFFFFFF' } };
      } else if (statusCell.value === 'Good') {
        statusCell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF3B82F6' } };
        statusCell.font = { color: { argb: 'FFFFFFFF' } };
      } else if (statusCell.value === 'Average') {
        statusCell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFF59E0B' } };
      } else {
        statusCell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFEF4444' } };
        statusCell.font = { color: { argb: 'FFFFFFFF' } };
      }
    });
    
    // Add borders to all cells
    worksheet.eachRow((row, rowNumber) => {
      if (rowNumber > 1) {
        row.eachCell((cell) => {
          cell.border = {
            top: { style: 'thin' },
            left: { style: 'thin' },
            bottom: { style: 'thin' },
            right: { style: 'thin' }
          };
        });
      }
    });
  }
  
  /**
   * Create KPIs Detail worksheet
   */
  static async createKPIsSheet(workbook, report) {
    const worksheet = workbook.addWorksheet('KPIs Detail');
    
    const data = report.reportData;
    const kpis = data.kpis || {};
    const comparison = data.comparativeAnalysis || {};
    
    // Set column widths
    worksheet.columns = [
      { key: 'kpi', width: 25 },
      { key: 'current', width: 15 },
      { key: 'previous', width: 15 },
      { key: 'change', width: 15 },
      { key: 'target', width: 15 },
      { key: 'achievement', width: 15 }
    ];
    
    // Add header
    const headerRow = worksheet.addRow(['KPI', 'Current Period', 'Previous Period', 'Change %', 'Target', 'Achievement %']);
    headerRow.font = { bold: true, color: { argb: 'FFFFFFFF' } };
    headerRow.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF2563EB' } };
    headerRow.alignment = { horizontal: 'center', vertical: 'middle' };
    
    // KPI comparison data
    const kpiComparison = [
      [
        'Total Revenue',
        this.formatCurrency(kpis.totalRevenue),
        this.formatCurrency(comparison.previousPeriod?.revenue || 0),
        this.formatPercentageChange(comparison.previousPeriod?.percentageChange || 0),
        this.formatCurrency(comparison.targetComparison?.revenueTarget || 0),
        this.formatPercentage(comparison.targetComparison?.achievementPercentage || 0)
      ],
      [
        'Total Leads',
        this.formatNumber(kpis.totalLeads),
        this.formatNumber(comparison.previousPeriod?.leads || 0),
        this.calculateChange(kpis.totalLeads, comparison.previousPeriod?.leads || 0),
        this.formatNumber(comparison.targetComparison?.leadsTarget || 0),
        this.calculateAchievement(kpis.totalLeads, comparison.targetComparison?.leadsTarget || 0)
      ],
      [
        'Conversion Rate',
        this.formatPercentage(kpis.conversionRate),
        this.formatPercentage(comparison.previousPeriod?.conversionRate || 0),
        this.calculateChange(kpis.conversionRate, comparison.previousPeriod?.conversionRate || 0),
        this.formatPercentage(comparison.targetComparison?.conversionTarget || 0),
        this.calculateAchievement(kpis.conversionRate, comparison.targetComparison?.conversionTarget || 0)
      ]
    ];
    
    kpiComparison.forEach(row => {
      const dataRow = worksheet.addRow(row);
      dataRow.getCell(1).font = { bold: true };
      
      // Format change column with colors
      const changeCell = dataRow.getCell(4);
      const changeValue = parseFloat(changeCell.value?.toString().replace('%', '') || 0);
      if (changeValue > 0) {
        changeCell.font = { color: { argb: 'FF10B981' } };
      } else if (changeValue < 0) {
        changeCell.font = { color: { argb: 'FFEF4444' } };
      }
      
      // Format achievement column with colors
      const achievementCell = dataRow.getCell(6);
      const achievementValue = parseFloat(achievementCell.value?.toString().replace('%', '') || 0);
      if (achievementValue >= 100) {
        achievementCell.font = { color: { argb: 'FF10B981' } };
      } else if (achievementValue >= 80) {
        achievementCell.font = { color: { argb: 'FFF59E0B' } };
      } else {
        achievementCell.font = { color: { argb: 'FFEF4444' } };
      }
    });
    
    // Add borders
    worksheet.eachRow((row) => {
      row.eachCell((cell) => {
        cell.border = {
          top: { style: 'thin' },
          left: { style: 'thin' },
          bottom: { style: 'thin' },
          right: { style: 'thin' }
        };
      });
    });
  }
  
  /**
   * Create Lead Analysis worksheet
   */
  static async createLeadAnalysisSheet(workbook, report) {
    const worksheet = workbook.addWorksheet('Lead Analysis');
    
    const leadSources = report.reportData.analytics?.leadSourceBreakdown || [];
    
    // Set column widths
    worksheet.columns = [
      { key: 'source', width: 20 },
      { key: 'count', width: 12 },
      { key: 'percentage', width: 12 },
      { key: 'converted', width: 12 },
      { key: 'conversionRate', width: 15 },
      { key: 'status', width: 15 }
    ];
    
    // Add header
    const headerRow = worksheet.addRow(['Lead Source', 'Total Leads', 'Percentage', 'Converted', 'Conversion Rate', 'Performance']);
    headerRow.font = { bold: true, color: { argb: 'FFFFFFFF' } };
    headerRow.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF059669' } };
    headerRow.alignment = { horizontal: 'center', vertical: 'middle' };
    
    // Add lead source data
    leadSources.forEach(source => {
      const row = worksheet.addRow([
        source.source,
        this.formatNumber(source.count),
        this.formatPercentage(source.percentage),
        this.formatNumber(source.converted || Math.floor(source.count * source.conversionRate / 100)),
        this.formatPercentage(source.conversionRate),
        this.getPerformanceStatus(source.conversionRate, 'conversion')
      ]);
      
      // Color code performance
      const statusCell = row.getCell(6);
      this.colorCodePerformance(statusCell, statusCell.value);
    });
    
    // Add summary row
    const totalLeads = leadSources.reduce((sum, source) => sum + source.count, 0);
    const totalConverted = leadSources.reduce((sum, source) => sum + (source.converted || Math.floor(source.count * source.conversionRate / 100)), 0);
    const overallConversion = totalLeads > 0 ? (totalConverted / totalLeads * 100) : 0;
    
    worksheet.addRow([]);
    const summaryRow = worksheet.addRow([
      'TOTAL',
      this.formatNumber(totalLeads),
      '100%',
      this.formatNumber(totalConverted),
      this.formatPercentage(overallConversion),
      this.getPerformanceStatus(overallConversion, 'conversion')
    ]);
    summaryRow.font = { bold: true };
    summaryRow.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFF3F4F6' } };
    
    // Add borders
    worksheet.eachRow((row) => {
      row.eachCell((cell) => {
        cell.border = {
          top: { style: 'thin' },
          left: { style: 'thin' },
          bottom: { style: 'thin' },
          right: { style: 'thin' }
        };
      });
    });
  }
  
  /**
   * Create Product Performance worksheet
   */
  static async createProductPerformanceSheet(workbook, report) {
    const worksheet = workbook.addWorksheet('Product Performance');
    
    const products = report.reportData.analytics?.productPerformance || [];
    
    // Set column widths
    worksheet.columns = [
      { key: 'product', width: 25 },
      { key: 'quotations', width: 12 },
      { key: 'sales', width: 12 },
      { key: 'revenue', width: 15 },
      { key: 'successRate', width: 15 },
      { key: 'avgDealSize', width: 15 },
      { key: 'performance', width: 15 }
    ];
    
    // Add header
    const headerRow = worksheet.addRow(['Product Name', 'Quotations', 'Sales', 'Revenue', 'Success Rate', 'Avg Deal Size', 'Performance']);
    headerRow.font = { bold: true, color: { argb: 'FFFFFFFF' } };
    headerRow.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF7C3AED' } };
    headerRow.alignment = { horizontal: 'center', vertical: 'middle' };
    
    // Add product data
    products.forEach(product => {
      const avgDealSize = product.sales > 0 ? product.revenue / product.sales : 0;
      const row = worksheet.addRow([
        product.productName,
        this.formatNumber(product.quotations),
        this.formatNumber(product.sales),
        this.formatCurrency(product.revenue),
        this.formatPercentage(product.successRate),
        this.formatCurrency(avgDealSize),
        this.getPerformanceStatus(product.successRate, 'success')
      ]);
      
      // Color code performance
      const statusCell = row.getCell(7);
      this.colorCodePerformance(statusCell, statusCell.value);
    });
    
    // Add totals
    const totalQuotations = products.reduce((sum, product) => sum + product.quotations, 0);
    const totalSales = products.reduce((sum, product) => sum + product.sales, 0);
    const totalRevenue = products.reduce((sum, product) => sum + product.revenue, 0);
    const overallSuccessRate = totalQuotations > 0 ? (totalSales / totalQuotations * 100) : 0;
    const overallAvgDeal = totalSales > 0 ? totalRevenue / totalSales : 0;
    
    worksheet.addRow([]);
    const totalRow = worksheet.addRow([
      'TOTAL',
      this.formatNumber(totalQuotations),
      this.formatNumber(totalSales),
      this.formatCurrency(totalRevenue),
      this.formatPercentage(overallSuccessRate),
      this.formatCurrency(overallAvgDeal),
      this.getPerformanceStatus(overallSuccessRate, 'success')
    ]);
    totalRow.font = { bold: true };
    totalRow.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFF3F4F6' } };
    
    // Add borders
    worksheet.eachRow((row) => {
      row.eachCell((cell) => {
        cell.border = {
          top: { style: 'thin' },
          left: { style: 'thin' },
          bottom: { style: 'thin' },
          right: { style: 'thin' }
        };
      });
    });
  }
  
  /**
   * Create Trends worksheet
   */
  static async createTrendsSheet(workbook, report) {
    const worksheet = workbook.addWorksheet('Trends');
    
    const dailyMetrics = report.reportData.trends?.dailyMetrics || [];
    
    // Set column widths
    worksheet.columns = [
      { key: 'date', width: 15 },
      { key: 'leads', width: 12 },
      { key: 'quotations', width: 12 },
      { key: 'sales', width: 12 },
      { key: 'revenue', width: 15 },
      { key: 'conversionRate', width: 15 }
    ];
    
    // Add header
    const headerRow = worksheet.addRow(['Date', 'Leads', 'Quotations', 'Sales', 'Revenue', 'Conversion %']);
    headerRow.font = { bold: true, color: { argb: 'FFFFFFFF' } };
    headerRow.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFDC2626' } };
    headerRow.alignment = { horizontal: 'center', vertical: 'middle' };
    
    // Add daily trend data
    dailyMetrics.forEach(day => {
      const conversionRate = day.leads > 0 ? (day.sales / day.leads * 100) : 0;
      worksheet.addRow([
        this.formatDate(day.date),
        this.formatNumber(day.leads),
        this.formatNumber(day.quotations),
        this.formatNumber(day.sales),
        this.formatCurrency(day.revenue),
        this.formatPercentage(conversionRate)
      ]);
    });
    
    // Add borders
    worksheet.eachRow((row) => {
      row.eachCell((cell) => {
        cell.border = {
          top: { style: 'thin' },
          left: { style: 'thin' },
          bottom: { style: 'thin' },
          right: { style: 'thin' }
        };
      });
    });
    
    // Add chart (if ExcelJS supports it)
    // This would create a line chart for trends
    try {
      const chart = worksheet.addImage({
        type: 'chart',
        range: 'H2:O15'
      });
    } catch (error) {
      // Chart creation not supported in this version
      console.log('Chart creation not supported');
    }
  }
  
  /**
   * Create Raw Data worksheet
   */
  static async createRawDataSheet(workbook, report) {
    const worksheet = workbook.addWorksheet('Raw Data');
    
    // This would contain raw data for further analysis
    worksheet.addRow(['Raw Data Export']);
    worksheet.addRow(['Report ID:', report.reportId]);
    worksheet.addRow(['Export Date:', this.formatDateTime(new Date())]);
    worksheet.addRow([]);
    
    // Add JSON data in readable format
    worksheet.addRow(['Report Configuration:']);
    worksheet.addRow(['Period:', `${this.formatDate(report.reportPeriod.startDate)} to ${this.formatDate(report.reportPeriod.endDate)}`]);
    worksheet.addRow(['Type:', report.reportType]);
    worksheet.addRow(['Category:', report.reportCategory]);
    worksheet.addRow([]);
    
    // Add filters if any
    if (report.filters && Object.keys(report.filters).length > 0) {
      worksheet.addRow(['Applied Filters:']);
      Object.entries(report.filters).forEach(([key, value]) => {
        worksheet.addRow([key, JSON.stringify(value)]);
      });
    }
  }
  
  /**
   * Helper formatting functions
   */
  static formatNumber(num) {
    return new Intl.NumberFormat('en-IN').format(num || 0);
  }
  
  static formatCurrency(amount) {
    return new Intl.NumberFormat('en-IN', {
      style: 'currency',
      currency: 'INR',
      minimumFractionDigits: 0,
      maximumFractionDigits: 0
    }).format(amount || 0);
  }
  
  static formatPercentage(percent) {
    return `${parseFloat(percent || 0).toFixed(1)}%`;
  }
  
  static formatPercentageChange(change) {
    const changeNum = parseFloat(change || 0);
    const sign = changeNum >= 0 ? '+' : '';
    return `${sign}${changeNum.toFixed(1)}%`;
  }
  
  static formatDate(date) {
    return new Date(date).toLocaleDateString('en-IN');
  }
  
  static formatDateTime(date) {
    return new Date(date).toLocaleString('en-IN');
  }
  
  static calculateChange(current, previous) {
    if (!previous || previous === 0) return '0%';
    const change = ((current - previous) / previous) * 100;
    return this.formatPercentageChange(change);
  }
  
  static calculateAchievement(current, target) {
    if (!target || target === 0) return '0%';
    const achievement = (current / target) * 100;
    return this.formatPercentage(achievement);
  }
  
  static getKPIStatus(value, type) {
    const numValue = parseFloat(value) || 0;
    
    switch (type) {
      case 'rate':
        if (numValue >= 25) return 'Excellent';
        if (numValue >= 20) return 'Good';
        if (numValue >= 15) return 'Average';
        return 'Poor';
      case 'revenue':
        if (numValue >= 1500000) return 'Excellent';
        if (numValue >= 1000000) return 'Good';
        if (numValue >= 500000) return 'Average';
        return 'Poor';
      case 'leads':
        if (numValue >= 50) return 'Excellent';
        if (numValue >= 35) return 'Good';
        if (numValue >= 20) return 'Average';
        return 'Poor';
      default:
        return 'Average';
    }
  }
  
  static getPerformanceStatus(value, type) {
    const numValue = parseFloat(value) || 0;
    
    if (type === 'conversion') {
      if (numValue >= 25) return 'Excellent';
      if (numValue >= 20) return 'Good';
      if (numValue >= 15) return 'Average';
      return 'Poor';
    }
    
    if (type === 'success') {
      if (numValue >= 40) return 'Excellent';
      if (numValue >= 30) return 'Good';
      if (numValue >= 20) return 'Average';
      return 'Poor';
    }
    
    return 'Average';
  }
  
  static colorCodePerformance(cell, status) {
    switch (status) {
      case 'Excellent':
        cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF10B981' } };
        cell.font = { color: { argb: 'FFFFFFFF' } };
        break;
      case 'Good':
        cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF3B82F6' } };
        cell.font = { color: { argb: 'FFFFFFFF' } };
        break;
      case 'Average':
        cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFF59E0B' } };
        break;
      case 'Poor':
        cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFEF4444' } };
        cell.font = { color: { argb: 'FFFFFFFF' } };
        break;
    }
  }
}

module.exports = ExcelReportService;

